package com.hyf.myhive;

public class TablesSql {

	public static String paymentjourna =
			"create table paymentjourna"
			+ " (paymentjournalid bigint"
			+ ", logisticsid bigint"
			+ ", logisticsname string"
			+ ", stationid  bigint"
			+ ", stationname string"
			+ ", enterprisememberid bigint"
			+ ", enterprisemembername string"
			+ ", bankloanflag int"
			+ ", loanbankid bigint"
			+ ", loanbankname string"
			+ ", cupcompanyid bigint"
			+ ", cupcompanyname string"
			+ ", acquirebankid bigint"
			+ ", acquirebankname string"
			+ ", settlementbankid bigint"
			+ ", settlementbankname string"
			+ ", paymentordername string"
			+ ", consignnoteid bigint"
			+ ", consignnotenum string"
			+ ", goodsreceived double"
			+ ", accountreceived double"
			+ ", receivedtype int"
			+ ", bank string"
			+ ", bankaccount string"
			+ ", bankcardtype int"
			+ ", state int"
			+ ", errorcode int"
			+ ", errordescription string"
			+ ", sendlogisticsid bigint"
			+ ", sendlogisticsname string"
			+ ", sendstationid bigint"
			+ ", sendstationname string"
			+ ", sendconsignnotenum string"
			+ ", staffid bigint"
			+ ", staffname string"
			+ ", merchantid string"
			+ ", masgetsettlementflag int"
			+ ", terminalnumber string"
			+ ", terminaldealid string"
			+ ", unionpaydealid string"
			+ ", paymenttype int"
			+ ", prepayflag int"
			+ ", settlementflag int"
			+ ", settlementtime string"
			+ ", settlementconfirmtime string"
			+ ", insteadflag int"
			+ ", businesstime string"
			+ ", checkflag int"
			+ ", checktime string"
			+ ", checkerrorcode int"
			+ ", checkdescription string"
			+ ", awardcompanysettlement double"
			+ ", rebatessettlement double"
			+ ", settlementerrorcode int"
			+ ", description string"
			+ ", createdby bigint"
			+ ", createdtime string"
			+ ", lastupdateby bigint"
			+ ", lastuptimestamp string"
			+ ", internalmerchantid string"
			+ ", internalterminalnumber string"
			+ ", terminaldealid2 string"
			+ ",terminaldealid3 string  )  "
			+ "row format delimited fields terminated by ' '";
			
	public static String mgsettlement_paymentjournal=
			"create table mgsettlement_paymentjournal("
			+ " 	  paymentjournalid bigint,"
			+ " 	  logisticsid bigint,"
			+ " 	  logisticsname string,"
			+ " 	  stationid bigint,"
			+ " 	  stationname string,"
			+ " 	  enterprisememberid bigint,"
			+ " 	  enterprisemembername string,"
			+ " 	  bankloanflag int,"
			+ " 	  loanbankid bigint,"
			+ " 	  loanbankname string,"
			+ " 	  cupcompanyid bigint,"
			+ " 	  cupcompanyname string,"
			+ " 	  acquirebankid bigint,"
			+ " 	  acquirebankname string,"
			+ " 	  settlementbankid bigint,"
			+ " 	  settlementbankname string,"
			+ " 	  paymentordername string,"
			+ " 	  consignnoteid bigint,"
			+ " 	  consignnotenum string,"
			+ " 	  goodsreceived double,"
			+ " 	  accountreceived double,"
			+ " 	  receivedtype int,"
			+ " 	  bank string,"
			+ " 	  bankaccount string,"
			+ " 	  bankcardtype int,"
			+ " 	  state int,"
			+ " 	  errorcode int,"
			+ " 	  errordescription string,"
			+ " 	  sendlogisticsid bigint,"
			+ " 	  sendlogisticsname string,"
			+ " 	  sendstationid bigint,"
			+ " 	  sendstationname string,"
			+ " 	  sendconsignnotenum string,"
			+ " 	  staffid bigint,"
			+ " 	  staffname string,"
			+ " 	  merchantid string,"
			+ " 	  masgetsettlementflag int,"
			+ " 	  terminalnumber string,"
			+ " 	  terminaldealid string,"
			+ " 	  unionpaydealid string,"
			+ " 	  paymenttype int,"
			+ " 	  prepayflag int,"
			+ " 	  settlementflag int,"
			+ " 	  settlementtime string,"
			+ " 	  settlementconfirmtime string,"
			+ " 	  insteadflag int,"
			+ " 	  businesstime string,"
			+ " 	  checkflag int,"
			+ " 	  checktime string,"
			+ " 	  checkerrorcode int,"
			+ " 	  checkdescription string,"
			+ " 	  awardcompanysettlement double,"
			+ " 	  rebatessettlement double,"
			+ " 	  settlementerrorcode int,"
			+ " 	  description string,"
			+ " 	  createdby bigint,"
			+ " 	  createdtime string,"
			+ " 	  lastupdateby bigint,"
			+ " 	  lastuptimestamp string,"
			+ " 	  internalmerchantid string,"
			+ " 	  internalterminalnumber string,"
			+ " 	  terminaldealid2 string,"
			+ " 	  terminaldealid3 string,"
			+ " 	  cal_id string"
			+ "	) row format delimited fields terminated by ' '";
	
	
	public static String company_hierarchy=
			"CREATE TABLE company_hierarchy"
			+"("
			+"  company_id bigint,"
			+"  f1_id bigint,"
			+"  f2_id bigint,"
			+"  f3_id bigint,"
			+"  f4_id bigint,"
			+"  f5_id bigint,"
			+"  f6_id bigint,"
			+"  f7_id bigint,"
			+"  f8_id bigint,"
			+" f9_id bigint,"
			+"  f10_id bigint,"
			+"  company_createdtime string,"
			+"  lastuptimestamp string,"
			+"  company_name string,"
			+"  f1_name string,"
			+"  f2_name string,"
			+"  f3_name string,"
			+"  f4_name string,"
			+"  f5_name string,"
			+"  f6_name string,"
			+"  f7_name string,"
			+"  f8_name string,"
			+"  f9_name string,"
			+"  f10_name string,"
			+"  agentflag int,"
			+"  createdtime string"
			+ "	) row format delimited fields terminated by ' '";
	
	
	public static String masget_dimension=
			"CREATE TABLE masget_dimension"
			+ "("
			+ "  companyid bigint,"
			+ "  companytypeid bigint,"
			+ "  companytypename string,"
			+ "  companyfirstsubtypeid bigint,"
			+ "  companyfirstsubtypename string,"
			+ "  companysecondsubtypeid bigint,"
			+ "  companysecondsubtypename string,"
			+ "  companyroleid bigint,"
			+ "  companyrolename string"
			+ "	) row format delimited fields terminated by ' '";
			
	public static String mgbase_calendar=		
			"CREATE TABLE mgbase_calendar"
			 + "("
			 + "  cal_id string,"
			 + "  cal_day int,"
			 + "  cal_full_day string,"
			 + "  cal_month_day string,"
			 + "  cal_week int,"
			 + "  cal_week_desc string,"
			 + "  cal_month int,"
			 + "  cal_year_day string,"
			 + "  cal_month_desc string,"
			 + "  cal_quarter int,"
			 + "  cal_quarter_desc string,"
			 + "  cal_year_quarter string,"
			 + "  cal_year int,"
			 + "  cal_year_desc string,"
			 + "  cal_day_of_week int,"
			 + "  cal_day_of_week_short_desc string,"
			 + "  cal_day_of_week_long_desc string"
			 + "	) row format delimited fields terminated by ' '";
			
	public static String mgbase_companyinfo=	
			"CREATE TABLE mgbase_companyinfo"
			+ "("
			+ "  companyid bigint,"
			+ "  companyname string,"
			+ "  companytypeid int,"
			+ "  companytypename string,"
			+ "  pcompanytypeid int,"
			+ "  pcompanytypename string,"
			+ "  provinceid int,"
			+ "  provincename string,"
			+ "  cityid int,"
			+ "  cityname string,"
			+ "  areaid int,"
			+ "  areaname string,"
			+ "  address string,"
			+ "  phone string,"
			+ "  faxnumber string,"
			+ "  introduction string,"
			+ "  icon string,"
			+ "  enableflag int,"
			+ "  createdtime string"
			+ "	) row format delimited fields terminated by ' '";
}

